const { resolve } = require('path')
const { readFileSync, writeFileSync } = require('fs')

module.exports = function(configuration) {
  const configPathForEnv = resolve(
    __dirname, `../../../config/config.${configuration}.ts`
  )
  const configPath = resolve(
    __dirname, `../../../config/config.ts`
  )
  const configFile = `// DO NOT EDIT. This file was generated by the 'ui-prebuild' `
    + `script.\n\n`
    + readFileSync(configPathForEnv, { encoding: 'utf-8' })

  writeFileSync(configPath, configFile)
}
