#!/usr/bin/env node

const { exec } = require('shelljs')
const { Command } = require('commander')
const { configToJson } = require('./config/helpers/config-to-json')

const {
  configuration,
  args: [ verb, secretKey, secretValue ]
} = new Command()
  .arguments('<add|delete> <secretKey> [secretValue]')
  .usage(
    `add <secretKey> <secretValue> -c <configuration> \n` +
    `       secrets delete <secretKey> -c <configuration>`
  )
  .option('-c, --configuration <configuration>', 'one of local, development, production')
  .parse(process.argv)

if (!configuration || !configuration.match(/^local$|^development$|^production$/)) {
  throw new Error(
    `You must provide a valid configuration to the --configuration flag (e.g. ` +
    `'development')`
  )
}

const { FIRE_PROJECT_ID } = configToJson(configuration)

if (verb === 'add') {
  exec(`
    ./berglas create ${FIRE_PROJECT_ID}-vault/${secretKey} ${secretValue} \
      --key projects/${FIRE_PROJECT_ID}/locations/global/keyRings/berglas/cryptoKeys/berglas-key
  `)
}

if (verb === 'delete') {
  exec(`
    ./berglas delete ${FIRE_PROJECT_ID}-vault/${secretKey}
  `)
}
