#!/usr/bin/env node
const { exec } = require('shelljs')
const program = require('commander')
const { readFileSync } = require('fs')
const admin = require('firebase-admin')
const { configToJson } = require('./config/helpers/config-to-json');

(async () =>
{
  program.option('-c, --configuration <configuration>', 'e.g. production')
  program.option('-k, --key <key>', 'e.g. DATABASE_PASSWORD or database-password')
  program.option('-v, --value <key>', 'e.g. password')
  program.parse(process.argv)
  const { configuration, key, value } = program.opts()
  const {
    FIRE_PROJECT_ID,
    LOCAL_PATH_TO_SERVICE_ACCOUNT_KEY,
  } = configToJson(configuration)
  const serviceAccount = require(LOCAL_PATH_TO_SERVICE_ACCOUNT_KEY)
  admin.initializeApp({
    credential: admin.credential.cert(serviceAccount)
  })

  const HOME = '/Users/danielmayer'
  const KMS_LOCATION = 'global'
  const KEY_RING_ID = FIRE_PROJECT_ID
  const KEY_ID = 'master'

  exec(`
    mkdir -p /Users/danielmayer/.funk-tmp/secrets
    echo ${value} >> ${HOME}/.funk-tmp/secrets/secret.txt
    gcloud kms encrypt --location ${KMS_LOCATION} \
      --keyring ${KEY_RING_ID} \
      --key ${KEY_ID} \
      --plaintext-file ${HOME}/.funk-tmp/secrets/secret.txt \
      --ciphertext-file ${HOME}/.funk-tmp/secrets/secret.txt.encrypted
  `)

  const encryptedSecret = readFileSync(`${HOME}/.funk-tmp/secrets/secret.txt.encrypted`,
    { encoding: 'utf-8' })

  admin.firestore().collection('vault').doc(key).set({ key, value: encryptedSecret })

  // Clean up.
  exec(`
    rm ${HOME}/.funk-tmp/secrets/secret.txt
    rm ${HOME}/.funk-tmp/secrets/secret.txt.encrypted
    rm -r ${HOME}/.funk-tmp/secrets
  `)
})()
