export const TAX_SERVICE_PROVIDER_SECRET_KEY = "TAX_SERVICE_PROVIDER_SECRET"
export const PAYMENT_SERVICE_PROVIDER_SECRET_KEY =
  "PAYMENT_SERVICE_PROVIDER_SECRET"
export const EMAIL_SERVICE_PROVIDER_SECRET_KEY = "EMAIL_SERVICE_PROVIDER_SECRET"
export const TURING_TEST_SERVICE_PROVIDER_SECRET_KEY =
  "TURING_TEST_SERVICE_PROVIDER_SECRET"
