import { resolve } from "path"
import { mkdirpSync, readFileSync, writeFileSync } from "fs-extra"
import { Configuration } from "../../../model/configuration"

export default function(configuration: Configuration)
{
  const configPathForEnv = resolve(
    __dirname, `../../../config/config.${configuration}.ts`
  )
  const configDirPaths = [
    resolve(__dirname, "../../../.funk/build-pipeline-output/config"),
  ]
  const configFile = "// DO NOT EDIT. This file was generated by the 'prebuild' "
    + "script.\n\n"
    + readFileSync(configPathForEnv, { encoding: "utf-8" })

  configDirPaths.forEach((configDirPath) =>
  {
    mkdirpSync(configDirPath)
    writeFileSync(resolve(configDirPath, "config.ts"), configFile)
  })
}
