const { resolve } = require('path')
const { mkdirpSync, readFileSync, writeFileSync } = require('fs-extra')

module.exports = function(configuration)
{
  const configPathForEnv = resolve(
    __dirname, `../../../config/config.${configuration}.ts`
  )
  const configDirPaths = [
    resolve(__dirname, `../../../.funk/build-pipeline-output/config`),
  ]
  const configFile = `// DO NOT EDIT. This file was generated by the 'prebuild' `
    + `script.\n\n`
    + readFileSync(configPathForEnv, { encoding: 'utf-8' })

  configDirPaths.forEach((configDirPath) =>
  {
    mkdirpSync(configDirPath)
    writeFileSync(resolve(configDirPath, 'config.ts'), configFile)
  })
}
