export const GCP_REGION = 'us-east1'
export const FUNCTIONS_REGION = 'us-central1'
export const FIRE_PROJECT_ID = 'funk-development'
export const TRUSTED_ORIGINS = 'http://localhost:4200,https://funk-development.firebaseapp.com'
export const PATH_TO_SERVICE_ACCOUNT_JSON = '/Users/danielmayer/.secrets/funk-development/funk-development-093bbbc44257.json'
