name: PR Build and Test

on:
  pull_request:
    branches: [ master ]

jobs:
  pr-test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm run build::development
      - run: npm test
